### ISSUE TITLE
Build process broken because of missing files

### ISSUE THREAD

**Issue by ronroberts** [nrasool/Gigya-Cordova-Demo#1]
Nadeem... I'm pretty sure you need to include plugins/fetch.json so that this will build properly. Also I don't think it would be a problem adding platforms/platforms.json. With both of these files present, everything should get downloaded and installed automatically upon first build.

Also, the gigyaClient.\* files in www/ are superfluous and could be removed. Cheers!

**Comment by nrasool** [comment]
Hey Ron, This has now been done. Cleaned up the project

Many thanks for pointing that out
